# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5531fa3c8c7f3fd92c4186d8bd4ed7da4882f3cca2f907931a5b3ae8043c810b9ccd07f11996e79750e47ab4788a4922158545fb5136fcb1a7b5f121f954686a

test:
  secret_key_base: 0a950ee28188a08f1f718cdcb9c879a25623311da0bf028a793de1bb682cf5dc510423c481bc1320e278773d6cce023b69177f07d5054945850050c6c33bbe74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
